# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Turing-PHD20
email: student-posters@turing.ac.uk
description:
baseurl: "/student-posters-2020" # the subpath of your site, e.g. /blog
url: "https://alan-turing-institute.github.io"

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap

exclude:
- Gemfile
- Gemfile.lock
- update_boostrap.sh
- node_modules
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/

# ---

conference:
  navigation:
    links:
      - name: Live sessions
        menu:
          - name: 17 Sep
            relative_url: /programme/session-1/
          - name: 24 Sep
            relative_url: /programme/session-2/
      - name: Posters
        menu:
          - name: 16-17 Sep
            relative_url: /showcases/session-1/
          - name: 23-24 Sep
            relative_url: /showcases/session-2/
      - name: Registration
        relative_url: /registration/
      - name: Author guidelines
        relative_url: /guidelines/

collections:
  showcases:
    permalink: /:collection/:title/
    output: true
  programme:
    permalink: /:collection/:title/
    output: true


defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: "assets/images"
    values:
      image: true
  - scope:
      path: ""
      type: "showcases"
    values:
      layout: "showcase"
  - scope:
      path: ""
      type: "programme"
    values:
      layout: "programme"
